---
title: "TP1"
author: "MIA0401V - Web - Initiation à l'écriture de pages dynamiques"
date: "L2 MIASHS - 2017/2018"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document: default
---


#Préambule

Pour les TP de la partie Web dynamique, vous devez toujours déposer vos fichiers .php sur le serveur Web mi-phpmut. Pour cela :

1. Utilisez un client SFTP (WinSCP, par exemple).
2. Connectez-vous au serveur `mi-phpmut.univ-tlse2.fr` à l’aide des identifiants que vous avez utilisés précédemment pour vous connecter sur `mass-cara2.univ-tlse2.fr` (l'UE du S1). 
3. Pour chaque TP vous allez créer un dossier `TPx` (où `x` est le numéro du TP). Vous devez toujours déposer les dossiers des TP dans le dossier `public_html` (créer ce dossier si il n’existe pas à la racine de votre home sur `mi-phpmut` et lui associer les droits pour qu’il soit accessible aux autres en exécution). 
4. Déposez les fichiers à réaliser pour le TP dans le dossier `TPx`.
5. Vos TP seront consultables à partir de l’url http://mi-phpmut.univ-tlse2.fr/~votre_identifiant/Tpx/nom_fichier.php 
(votre_identifiant correspondant au login que vous utilisez pour vous connecter à mi-phpmut et nom_fichier.php au fichier que vous avez déposé).

#Exercice 1

Modifiez la page d'accueil du site de votre projet pour que s'affiche le texte « Bonjour, nous sommes le » suivi de la date du jour. Pour cela :

1. Renommez le fichier `index.html` présent sur votre disque dur en `index.php`.
2. Intégrez dans le fichier `index.php` le code PHP nécessaire pour afficher le texte. 
3. Visualisez le contenu de la page `index.php` (que vous laissez sur votre disque dur) dans le navigateur. Que constatez-vous ?
4. Déposez le fichier `index.php` sur le serveur `mi-phpmut`. Visualisez dans le navigateur votre nouvelle page d'accueil.
5. Modifiez le code PHP pour que le texte « Bonjour, nous sommes le [date] » suivi de la date, soit encadré par des balises `<h2>`. Déposez la nouvelle version du fichier sur le serveur et visualisez à nouveau votre page.
6. Modifiez le code PHP et le fichier css pour que le texte apparaisse en gras et en couleur de votre choix. Déposez les fichiers sur le serveur.

#Exercice 2

1. Créez le répertoire `TP1` dans le répertoire `public_html`.
2. Créez ensuite la page `version.php`, qui écrit la version de PHP utilisée par le serveur Web et le nom de son système d'exploitation. Pour cela, créez deux variables, qui recevront les valeurs des constantes PHP `PHP_VERSION` et `PHP_OS`. Affichez les valeurs des deux variables créées. 
Quelle version de PHP et quel système d'exploitation `mi-phpmut` utilise-t-il ?



#Exercice 3

1. Créez la page `informatique.php`. Cette page doit afficher les différents jours de la semaine et pour chacun d’entre-eux l'information indiquant si vous avez cours d'informatique ce jour-là ou pas. Pour cela :
    a. créez un tableau associatif ayant comme clé le nom des jours de la semaine (« jeudi », par exemple) et comme valeur une chaîne de caractères indiquant si vous avez cours d'informatique ou pas. Vous devez ensuite parcourir le tableau associatif et afficher son contenu. Déposez le fichier sur le serveur et visualisez-le  dans le navigateur. 
    b. affichez le contenu du tableau associatif dans un tableau, en utilisant les balises `<table>`, `<th>`, `<td>`, etc.

2. Vous allez modifier le texte de votre page d'accueil ([exercice 1](#exercice-1)), de façon à afficher « Bonjour, nous sommes le [jour de la semaine] [date] », par exemple, « Bonjour, nous sommes le jeudi 26/01/2018». Pour cela :
    a. créez un tableau associatif ayant comme clé le numéro du jour de la semaine (1 à 7) et comme valeur le nom du jour de la semaine (« lundi » à « dimanche »).
    b. l'affichage doit marcher pour n'importe quel jour de la semaine. Utilisez la fonction date("N") définie en PHP et qui retourne le jour courant de la semaine, de 1 (pour Lundi) à 7 (pour Dimanche).


